name: CI/CD Operations

on:
  push:
    branches:
      - main  
      - develop
      - uat

jobs:
  build-infra:
    name: Build Infrastructure
    runs-on: ubuntu-latest
    environment: ${{github.ref_name}}
    env:
      Azure_ClientId: ${{ secrets.Azure_ClientId }}
      Azure_ClientSecret: ${{ secrets.Azure_ClientSecret }}
      Azure_TenantId: ${{ secrets.Azure_TenantId }}
      Azure_SubcriptionId: ${{ secrets.Azure_SubcriptionId }}
    steps:
      - name: Get secret values
        run: |
          echo ${{ github.ref_name}}  | sed 's/./& /g'
          echo "Azure_ClientId:" $Azure_ClientId  | sed 's/./& /g'
          echo "Azure_ClientSecret:" $Azure_ClientSecret  | sed 's/./& /g'
          echo "Azure_TenantId:" $Azure_TenantId  | sed 's/./& /g'
          echo "Azure_SubcriptionId:" $Azure_SubcriptionId  | sed 's/./& /g'
      - name: Azure check out
        uses: actions/checkout@v2
      - name: Setup the Infrastructure in Azure
        run: |
          az login --service-principal --username "$Azure_ClientId" --password "$Azure_ClientSecret" --tenant "$Azure_TenantId"
          az deployment sub create --subscription "$Azure_SubcriptionId" --name cbam-deployment --location eastus --template-file bicep/main.bicep --parameters bicep/parameters-dev.json --parameters env=temp

  deploy-app:
    needs: build-infra
    runs-on: ubuntu-latest
    environment: ${{github.ref_name}}
    env:
      Azure_WebApp: ${{ secrets.Azure_WebApp }}
      Azure_ClientId: ${{ secrets.Azure_ClientId }}
      Azure_ClientSecret: ${{ secrets.Azure_ClientSecret }}
      Azure_TenantId: ${{ secrets.Azure_TenantId }}
      Azure_SubcriptionId: ${{ secrets.Azure_SubcriptionId }}
    steps:
      - name: Get secrets values 
        run: |
          echo $Azure_WebApp  | sed 's/./& /g'
          echo "Azure_ClientId:" $Azure_ClientId  | sed 's/./& /g'
          echo "Azure_ClientSecret:" $Azure_ClientSecret  | sed 's/./& /g'
          echo "Azure_TenantId:" $Azure_TenantId  | sed 's/./& /g'
          echo "Azure_SubcriptionId:" $Azure_SubcriptionId  | sed 's/./& /g'
          echo "{\"clientId\":\"$Azure_ClientId\",\"clientSecret\":\"$Azure_ClientSecret\",\"subscriptionId\":\"$Azure_SubcriptionId\",\"tenantId\":\"$Azure_TenantId\"}" | sed 's/./& /g'
      - name: Do checkout      
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "microsoft"
      - name: Build with Maven
        run: mvn clean package -DoutputDirectory=./target
      - name: Azure Login
        uses: azure/login@v2
        with:
          auth-type: "SERVICE_PRINCIPAL"
          creds: "{\"clientId\":\"$Azure_ClientId\",\"clientSecret\":\"$Azure_ClientSecret\",\"subscriptionId\":\"$Azure_SubcriptionId\",\"tenantId\":\"$Azure_TenantId\"}" 
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "$Azure_WebApp"
          package: 'target/*.jar'