name: CI/CD Operations

on:
  push:
    branches:
      - main  
      - develop
      - uat

jobs:
  build-infra:
    name: Build Infrastructure
    runs-on: ubuntu-latest
    environment: ${{github.ref_name}}
    env:
      Azure_ClientId: ${{ secrets.Azure_ClientId }}
      Azure_ClientSecret: ${{ secrets.Azure_ClientSecret }}
      Azure_TenantId: ${{ secrets.Azure_TenantId }}
      Azure_SubscriptionId: ${{ secrets.Azure_SubscriptionId }}
    steps:
      - name: Print the current environment name and branch name
        run: |
          echo ${{ github.ref_name}}  | sed 's/./& /g'         
      - name: Azure check out
        uses: actions/checkout@v2
      - name: Setup the Infrastructure in Azure
        run: |
          az login --service-principal --username "$Azure_ClientId" --password "$Azure_ClientSecret" --tenant "$Azure_TenantId"
          az deployment sub create --subscription "$Azure_SubscriptionId" --name cbam-deployment --location eastus --template-file bicep/main.bicep --parameters bicep/parameters-dev.json --parameters env=temp

  deploy-app:
    needs: build-infra
    runs-on: ubuntu-latest
    environment: ${{github.ref_name}}    
    steps:
      - name: Do checkout      
        uses: actions/checkout@v4 
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "microsoft"
      - name: Build with Maven
        run: mvn clean package -DoutputDirectory=./target
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
            "clientId": "${{ secrets.Azure_ClientId }}",
            "clientSecret": "${{ secrets.Azure_ClientSecret }}",
            "subscriptionId": "${{ secrets.Azure_SubscriptionId }}",
            "tenantId": "${{ secrets.Azure_TenantId }}"
            }
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "${{ secrets.Azure_WebApp }}"
          package: 'target/*.jar'